package com.samiun.mycricket.model.fixturewithdetails

data class FixtureWithDetailsData(
    var balls: List<Ball>?,
    var batting: List<Batting>?,
    var bowling: List<Bowling>?,
    var draw_noresult: Any?,
    var elected: String?,
    var first_umpire_id: Int?,
    var follow_on: Boolean?,
    var id: Int?,
    var last_period: Any?,
    var league_id: Int?,
    var lineup: List<Lineup>?,
    var live: Boolean?,
    var localteam_dl_data: LocalteamDlData?,
    var localteam_id: Int?,
    var man_of_match_id: Int?,
    var man_of_series_id: Any?,
    var note: String?,
    var referee_id: Int?,
    var resource: String?,
    var round: String?,
    var rpc_overs: Any?,
    var rpc_target: Any?,
    var season_id: Int?,
    var second_umpire_id: Int?,
    var stage_id: Int?,
    var starting_at: String?,
    var status: String?,
    var super_over: Boolean?,
    var toss_won_team_id: Int?,
    var total_overs_played: Int?,
    var tv_umpire_id: Int?,
    var type: String?,
    var venue_id: Int?,
    var visitorteam_dl_data: VisitorteamDlData?,
    var visitorteam_id: Int?,
    var weather_report: List<Any>?,
    var winner_team_id: Int?
){

        constructor():this(
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
        )
}